<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInitaf7eedd6a326e7743a90066cf2793a09
{
    public static $prefixLengthsPsr4 = array (
        'M' => 
        array (
            'MessageBird\\' => 12,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'MessageBird\\' => 
        array (
            0 => __DIR__ . '/..' . '/messagebird/php-rest-api/src/MessageBird',
        ),
    );

    public static $classMap = array (
        'Composer\\InstalledVersions' => __DIR__ . '/..' . '/composer/InstalledVersions.php',
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInitaf7eedd6a326e7743a90066cf2793a09::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInitaf7eedd6a326e7743a90066cf2793a09::$prefixDirsPsr4;
            $loader->classMap = ComposerStaticInitaf7eedd6a326e7743a90066cf2793a09::$classMap;

        }, null, ClassLoader::class);
    }
}
